### ISSUE TITLE
画像の投稿をわかりやすくしたい

### ISSUE THREAD

**Issue by taigaozawa** [nnn-training/faq#12]
### 概要
今は `/public` ディレクトリに直接追加することで画像を表示できるが、わかりにくい。

### 改善案

- `MARKDOWN/{中間ディレクトリ}/` 内に画像ファイルを保存すると、`yarn build` 時に `/public/imgaes/{中間ディレクトリ}/` に画像をコピーする機能を追加
- マークダウンには `[](./画像名.png)` と書けば良いようにする

### 参考

https://24365.dev/posts/20211015-nextjs-image-dir/

**Comment by dorimiamn** [comment]
コピーするのは負荷が重そうだなと感じたので、markdown -> HTML への変換時にリンクをよしなに変換できる方法で実装できたらと思います。(数が少ないので気にする必要はあまりないかもしれませんが……。)

unified 関連のプラグインで利用できるものがありそうです。

### 参考
https://qiita.com/sankentou/items/f8eadb5722f3b39bbbf8
https://blog.ryou103.com/post/next-js-markdown-image/
https://kenzoblog.vercel.app/posts/nextjs-blog-asset

**Comment by TrpFrog** [comment]
Next.js の[ドキュメント](https://nextjs.org/docs/pages/building-your-application/optimizing/static-assets) には

> The directory must be named public. The name cannot be changed and it's the only directory used to serve static assets.

とあり、どうやら静的ファイルは**必ず** `/public` の下に置かないといけないみたいです。
ですので、画像をコピーするのは仕方がないかもしれません……。

無理やりな解決としては `MARKDOWN` 自体を public の中にお引越しする方法がありそうですが、パワープレイすぎる気もします。(このリポジトリは public なので問題ないとは思いますが、Markdown ファイルまで公開されてしまうため)

**Comment by dorimiamn** [comment]
あー、リンクだけ変換しても画像ファイルの場所自体を public に置かないとですから意味ないんですね……。

> 無理やりな解決としては MARKDOWN 自体を public の中にお引越しする方法がありそうですが、パワープレイすぎる気もします。(このリポジトリは public なので問題ないとは思いますが、Markdown ファイルまで公開されてしまうため)

確かにパワープレイなので、とりあえずコピーする方法で実装します。
情報ありがとうございます！
