### ISSUE TITLE
npx prisma コマンドが失敗する問題の FAQ を更新したい。

### ISSUE THREAD

**Issue by dorimiamn** [nnn-training/faq#60]
https://github.com/docker/for-mac/issues/6824

Docker Desktop のバージョンを v4.18.0 にすれば問題なく動作することを確認しており、都度 Node のバージョンを下げるよりは手間がないため、Docker Desktop のバージョンを下げる内容に変更したい。

**Comment by alcnaka** [comment]
上記Issueから来ました。
下記対応によってもSegmentation Faultは発生しなくなります。

* Virtualization Frameworkの無効化
* 上記のためのファイル共有のVirtioFS -> gRPC FUSEへの変更

Docker Desktopのバージョンを下げずに設定の変更のみで済むので、より手間がないかと思います。

たまたま上記のIssueで見かけたのでコメントさせていただきましたが、もしご参考になれば幸いです。

**Comment by dorimiamn** [comment]
情報ありがとうございます！

Virtualization Framework は無効化できないものと考えていましたが、 VirtioFS が仮想マシン間の I/O フレームワークであり、これを指していたんですね。
手元で確認したところ General より簡単に変更できますので、教えていただいた方法を使いたいと思います。
助かりました！
