### ISSUE TITLE
ページ遷移時に、 tsx ファイル中にある画像が表示されない場合がある

### ISSUE THREAD

**Issue by dorimiamn** [nnn-training/faq#64]
ページ遷移時に、画像用のパスがローカル用になってしまい、表示されない場合がある。
再読み込みするとデプロイ環境用のパスに戻る。

マークダウンで記述したファイル内の画像は正常に表示される。

Next.js の SSG を使ってサイトを生成しているはずだからこのような変化は起きないはず？

~Actions 当たりを確認してどのようにデプロイされているか確認したらわかりそう~
`gh-pages` ブランチを参照したが、元のファイルはやはりデプロイ用環境パスが記述されていて、切り替わりそうな部分がない。

~単にキャッシュの問題かも~
スーパーリロードしても変わらず。一旦保留

**Comment by mikrogeophagus** [comment]
#80 で解決できたようなのでクローズします 🙇
