### ISSUE TITLE
画像がリンク切れしている

### ISSUE THREAD

**Issue by moesuke** [nnn-training/faq#71]
N予備校のロゴなど

**Comment by mikrogeophagus** [comment]
内部リンクから移動してきた場合に `GITHUB_PAGES` で出し分けている画像が壊れるようです。
https://github.com/nnn-training/faq/blob/67e8cfbab6ffb82a1fc9b42cfcc760c23872ab16/src/components/Layout.tsx#L25

例えば `nyobiko.png` のパスが内部リンクからアクセスした場合と直接アクセスした場合で異なります。

- 内部リンクからアクセスした場合:  `/images/nyobiko.png`
- 直接アクセスした場合・リロードした場合: `/faq/images/nyobiko.png`

**Comment by mikrogeophagus** [comment]
内部リンクからアクセスした場合 `GITHUB_PAGES` が `undefined` なのかもしれない？
自信はありませんが、だめ元で `NEXT_PUBLIC_` を付けてみようと思います。

**Comment by mikrogeophagus** [comment]
直りました！！
クローズします。

**Comment by moesuke** [comment]
ありがとうございました！
